# Generated by Django 3.2.6 on 2022-05-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0003_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
