# Generated by Django 3.2.6 on 2022-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0003_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
