# Generated by Django 3.2.6 on 2022-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0003_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
