# Generated by Django 3.2.6 on 2022-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0004_doctor_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='result',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
    ]
