# Generated by Django 3.2.6 on 2022-04-25 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital_hub.city')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='hospital',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='my_admins', to='hospital_hub.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_doctors', to='hospital_hub.hospital'),
        ),
    ]
