# Generated by Django 3.2.6 on 2022-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0006_auto_20220425_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
