# Generated by Django 3.2.6 on 2022-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0007_auto_20220425_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='specialities',
            field=models.ManyToManyField(to='hospital_hub.Speciality'),
        ),
    ]
