# Generated by Django 3.2.6 on 2022-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0009_speciality_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='image',
        ),
    ]
