# Generated by Django 3.2.6 on 2022-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0010_auto_20220427_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtest',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
    ]
