# Generated by Django 3.2.6 on 2022-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0011_alter_imgtest_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imgtest',
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
    ]
