# Generated by Django 3.2.6 on 2022-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0016_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default='no_hospital_img.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='no_profile_img.png', upload_to='media/'),
        ),
    ]
