# Generated by Django 4.0.4 on 2022-04-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0018_alter_hospital_image_alter_hospital_specialities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_admins', to='hospital_hub.hospital'),
        ),
    ]
