# Generated by Django 3.2.6 on 2022-05-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0019_alter_admin_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='specialities',
            field=models.ManyToManyField(blank=True, null=True, to='hospital_hub.Speciality'),
        ),
    ]
