# Generated by Django 3.2.6 on 2022-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_hub', '0020_alter_hospital_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(),
        ),
    ]
